version: '3.8'

services:
  cardservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cardservice
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    networks:
      - card_network

networks:
  card_network:
    driver: bridge
